### ISSUE TITLE
Crosswalk 23 building issue in Linux.

### ISSUE THREAD

**Issue by NitzDKoder** [crosswalk-project/crosswalk#3986]
1) Trying to build crosswalk-23 under linux machine,folowed below instructions
https://crosswalk-project.org/contribute/building_crosswalk/android_build.html
2) on calling gclient sync ,checkout is failing with below error
*________ running '/usr/bin/python src/xwalk/gyp_xwalk' in '/home/kodiak/Desktop/Xwalkbuild'
Skipping gyp_xwalk due to GYP_CHROMIUM_NO_ACTION env var.*
Build machine info:
Distributor ID:	Ubuntu
Release:	16.04
Codename:	xenial
Architecture: x86_64

**Comment by rakuco** [comment]
That's not an error message. Please check the rest of your `gclient sync` log for the actual issue.

**Comment by kusumakara** [comment]
**once gclient sync done**  I am trying to build with below command

**ninja -C out_Release/Release xwalk_core_library_aar**

But its  stop with below error:

ninja: Entering directory `out_Release/Release'
[1/8] SOLINK ./libxwalkcore.so
FAILED: libxwalkcore.so libxwalkcore.so.TOC lib.unstripped/libxwalkcore.so 
python "/home/kodiak/Desktop/CrossWalk/src/build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-readelf" --nm="../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm" --strip=../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --sofile="./lib.unstripped/libxwalkcore.so" --tocfile="./libxwalkcore.so.TOC" --output="./libxwalkcore.so" -- ../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -fuse-ld=gold -Wl,--icf=all -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libc++_static.a -Wl,--exclude-libs=libvpx_assembly_arm.a -Wl,--warn-shared-textrel -Wl,-O1 -Wl,--as-needed -nostdlib -Wl,--warn-shared-textrel --sysroot=../../third_party/android_tools/ndk/platforms/android-16/arch-arm  -Wl,--version-script=/home/kodiak/Desktop/CrossWalk/src/build/android/android_no_jni_exports.lst -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -L../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -o "./lib.unstripped/libxwalkcore.so" -Wl,-soname="libxwalkcore.so" @"./libxwalkcore.so.rsp"
collect2: error: ld terminated with signal 9 [Killed]
ninja: build stopped: subcommand failed.

Please any one help me thanks....

**Comment by rakuco** [comment]
> collect2: error: ld terminated with signal 9 [Killed]

It just looks like you've run out of memory while linking libxwalkcore.so.

**Comment by NitzDKoder** [comment]
@rakuco are you talking about RAM here? whats the minimum requirement to build crosswalk..currently we are using 4GB RAM..
Pls share your thoughts? have you ever built one on Linux machine before?

![mem](https://cloud.githubusercontent.com/assets/1461456/25524436/349c28d8-2c28-11e7-8adb-c59d87644e0f.JPG)

Thanks

**Comment by rakuco** [comment]
4gb is too little. You can assume the Chromium requirements from https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md#System-requirements also apply to Crosswalk, so consider 8gb a very minimum for a successful build.

**Comment by NitzDKoder** [comment]
@rakuco thanks..will update on this soon..

**Comment by fengcai** [comment]
@NitzDKoder have you build crosswalk23 on Ubuntu16.04 LTS successfully?

can you share your Ubuntu info, the following is mine:
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
wwcheng@WWCHENG-CN:/mnt/d/xwalk/src$ uname -a
Linux WWCHENG-CN 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux


I am wondering if you run into the following issues 
**Error Info**
$ ninja -C out/Default xwalk
ninja: Entering directory `out/Default'
[26/14529] ACTION //content/public/android:common_aidl(//build/toolchain/android:arm)
FAILED: gen/content/public/android/common_aidl.d gen/content/public/android/common_aidl.srcjar
python ../../build/android/gyp/aidl.py --depfile gen/content/public/android/common_aidl.d --aidl-path ../../third_party/android_tools/sdk/build-tools/23.0.1/aidl --imports=["../../third_party/android_tools/sdk/platforms/android-23/framework.aidl",\ "../../content/public/android/java/src/org/chromium/content/common/common.aidl"] --srcjar gen/content/public/android/common_aidl.srcjar --includes=["../../content/public/android/java/src"] ../../content/public/android/java/src/org/chromium/content/common/IChildProcessCallback.aidl ../../content/public/android/java/src/org/chromium/content/common/IChildProcessService.aidl
Traceback (most recent call last):
File "../../build/android/gyp/aidl.py", line 62, in
sys.exit(main(sys.argv))
File "../../build/android/gyp/aidl.py", line 45, in main
build_utils.CheckOutput(aidl_cmd)
File "/mnt/d/xwalk/src/build/android/gyp/util/build_utils.py", line 164, in CheckOutput
stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)
File "/usr/lib/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 8] Exec format error
[31/14529] CXX obj/crypto/crypto/aead.o
ninja: build stopped: subcommand failed.

thanks and looking forward your feedback.
