### ISSUE TITLE
TextureView doesn't support displaying background drawable

### ISSUE THREAD

**Issue by chnouman** [crosswalk-project/crosswalk#4039]
on above API 23 I'm facing this issue.

```
java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
at android.view.TextureView.setBackgroundDrawable(TextureView.java:315)
at android.view.View.setBackground(View.java:18124)
at android.view.View.<init>(View.java:4573)
at android.view.View.<init>(View.java:4082)
at android.view.TextureView.<init>(TextureView.java:159)
at com.abdulwasaetariq.xyz.ui.customView.AutoFitTextureView.<init>(AutoFitTextureView.java:24)
at com.abdulwasaetariq.xyz.ui.customView.AutoFitTextureView.<init>(AutoFitTextureView.java:20)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[...]
at java.lang.Thread.run(Thread.java:745)
```

If there is any fix please provide.

**Comment by dev-kang** [comment]
I have the same issue, can anyone help me?

**Comment by chnouman** [comment]
@dev-kang I used webview at the end.
